Airlines.Web/Models/AirlineViewModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Airlines.Web.Models;

public class AirlineViewModel
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string? Name { get; set; }

    public DateOnly? Founded { get; set; }

    public int? FleetSize { get; set; }

    [StringLength(2048)]
    public string? Description { get; set; }
}

Airlines.Web/Models/AirportViewModel.cs
using Airlines.Persistance.Models;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Airlines.Web.Models;

public class AirportViewModel
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(256)]
    public string? Name { get; set; }

    [StringLength(256)]
    public string? Country { get; set; }

    [StringLength(256)]
    public string? City { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string? Code { get; set; }

    public int? RunwaysCount { get; set; }

    public DateOnly? Founded { get; set; }

    [InverseProperty("ArrivalAirport")]
    public virtual ICollection<Flight> FlightArrivalAirports { get; set; } = new List<Flight>();

    [InverseProperty("DepartureAirport")]
    public virtual ICollection<Flight> FlightDepartureAirports { get; set; } = new List<Flight>();
}

Airlines.Web/Models/ErrorViewModel.cs
namespace Airlines.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Airlines.Web/Models/FlightViewModel.cs
using Airlines.Persistance.Models;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Airlines.Web.Models;

public class FlightViewModel
{
    [Key]
    public int Id { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string? FlightNumber { get; set; }
    public int? DepartureAirportId { get; set; }

    public int? ArrivalAirportId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DepartureDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ArrivalDateTime { get; set; }

    public string? From { get; set; }
    public string? To { get; set; }

    [ForeignKey("ArrivalAirportId")]
    [InverseProperty("FlightArrivalAirports")]
    public virtual Airport? ArrivalAirport { get; set; }

    [ForeignKey("DepartureAirportId")]
    [InverseProperty("FlightDepartureAirports")]
    public virtual Airport? DepartureAirport { get; set; }
}

Airlines.Web/Controllers/AirlineController.cs
using Airlines.Persistance.Models;
using Microsoft.AspNetCore.Mvc;
using Airlines.Business.Services;

namespace Airlines.Web.Controllers;
public class AirlineController : Controller
{
    private readonly AirlineService _airlineService;
    public AirlineController(AirlineService airlineService)
    {
        _airlineService = airlineService;
    }
    public IActionResult Index()
    {
        List<Airline> airlineList = _airlineService.GetAirlines();
        return View(airlineList);
    }

    [HttpPost]
    public ActionResult CreateNewAirline(Airline airline)
    {
        if (airline.Founded.HasValue && airline.Founded.Value > DateOnly.FromDateTime(DateTime.Today))
        {
            ModelState.AddModelError("Founded", "Invalid date.");
        }
        if (ModelState.IsValid)
        {
            _airlineService.AddAirlineToDB(airline);
            TempData["SuccessMessage"] = "Airline added successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["ErrorMessage"] = "The Airline was not added";
        List<Airline> airlineList = _airlineService.GetAirlines();
        return View("Index", airlineList);
    }

    public IActionResult Search(string searchTerm)
    {
        List<Airline> airlines = _airlineService.SearchInAirline(searchTerm);
        return View("Index", airlines);
    }
}

Airlines.Web/Controllers/AirportController.cs
using Airlines.Persistance.Models;
using Airlines.Persistence.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Airlines.Business.Services;

namespace Airlines.Web.Controllers;
public class AirportController : Controller
{
    private readonly AirportService _airportService;
    public AirportController(AirportService airportService)
    {
        _airportService = airportService;
    }
    public IActionResult Index()
    {
        List<Airport> airportList = _airportService.GetAirports();
        return View(airportList);
    }

    [HttpPost]
    public ActionResult CreateNewAirport(Airport airport)
    {
        if (airport.Founded.HasValue && airport.Founded.Value > DateOnly.FromDateTime(DateTime.Today))
        {
            ModelState.AddModelError("Founded", "Invalid date.");
        }
        if (ModelState.IsValid)
        {
            _airportService.AddAirportToDB(airport);
            TempData["SuccessMessage"] = "Airport added successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["ErrorMessage"] = "The Airport was not added";
        List<Airport> airportList = _airportService.GetAirports();
        return View("Index", airportList);
    }

    public IActionResult Search(string searchTerm)
    {
        List<Airport> airports = _airportService.SearchInAirport(searchTerm);
        return View("Index", airports);
    }
}

Airlines.Web/Controllers/FlightController.cs
using Airlines.Persistance.Models;
using Microsoft.AspNetCore.Mvc;
using Airlines.Business.Services;

namespace Airlines.Web.Controllers;
public class FlightController : Controller
{
    private readonly FlightService _flightService;
    public FlightController(FlightService flightService)
    {
        _flightService = flightService;
    }
    public IActionResult Index()
    {
        List<Flight> flightList = _flightService.GetFlights();
        return View(flightList);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult AddFlight(Flight flight)
    {
        if (flight.DepartureDateTime.HasValue && flight.DepartureDateTime.Value < DateTime.Now)
        {
            ModelState.AddModelError("DepartureDateTime", "Departure time must be in the future.");
        }

        if (flight.ArrivalDateTime.HasValue && flight.ArrivalDateTime.Value <= flight.DepartureDateTime)
        {
            ModelState.AddModelError("ArrivalDateTime", "Arrival time must be after the departure time.");
        }

        if (ModelState.IsValid)
        {
            _flightService.AddFlightToDB(flight);
            TempData["SuccessMessage"] = "Flight added successfully";
            return RedirectToAction(nameof(Index));
        }
        TempData["ErrorMessage"] = "The Flight was not added";
        List<Flight> flightList = _flightService.GetFlights();
        return View("Index", flightList);
    }

    public IActionResult Search(string searchTerm)
    {
        List<Flight> flight = _flightService.SearchInFlight(searchTerm);
        return View("Index", flight);
    }
}

Airlines.Web/Controllers/HomeController.cs
using Airlines.Business.Services;
using Airlines.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Airlines.Web.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly AirlineService _airlineService;
    private readonly AirportService _airportService;
    private readonly FlightService _flightService;

    public HomeController(ILogger<HomeController> logger, AirlineService airlineService,
        AirportService airportService, FlightService flightService)
    {
        _logger = logger;
        _airlineService = airlineService;
        _airportService = airportService;
        _flightService = flightService;
    }

    public IActionResult Index()
    {
        int airlineCount = _airlineService.GetAirlinesCount();
        int airportCount = _airportService.GetAirportsCount();
        int flightCount = _flightService.GetFlightsCount();

        // Pass the counts to the view
        ViewBag.AirlineCount = airlineCount;
        ViewBag.AirportCount = airportCount;
        ViewBag.FlightCount = flightCount;

        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Airlines.Web/Views/Airline/Index.cshtml
@model List<Airlines.Persistance.Models.Airline>
<partial name="_Notification" />

@{
    ViewData["Title"] = "Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-airlines">
    <div class="container-title">
        <a asp-controller="Home" asp-action="Index">
            <img src="~/Pictures/left sidebar.png" />
        </a>
        <h1>Airlines</h1>
        <div></div>
    </div>

    <div class="container-head"></div>

    <div id="showSearchBar">
        <form action="@Url.Action("Search", "Airline")" method="get" class="search-form">
            <input type="text" name="searchTerm" placeholder="Search..." class="search-input" />
            <button type="submit" class="search-button">Search</button>
        </form>
    </div>

    <div class="table">
        <table>
            <thead>
                <tr>
                    <th class="table-header">Name</th>
                    <th class="table-header">Founded</th>
                    <th class="table-header">Fleet size</th>
                    <th class="table-header">Description</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var airline in Model)
                {
                    <tr>
                        <td>@airline.Name</td>
                        <td>@airline.Founded</td>
                        <td>@airline.FleetSize</td>
                        <td class="data-cell">@airline.Description</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <button id="showMore" class="block-button-airlines">Show More</button>
    <a href="#" id="toggleButton" class="block-button-airlines">Show Form</a>

    @using (Html.BeginForm("CreateNewAirline", "Airline", FormMethod.Post, new { @class = "form" }))
    {
        <legend>Add new Airline</legend>

        <label for="name">Name</label>
        <input type="text" id="name" name="Name" required />
        <div class="text-danger" id="nameError"></div>

        <label for="founded">Founded</label>
        <input type="date" id="founded" name="Founded" required />
        <div class="text-danger" id="foundedError"></div>

        <label for="fleet_size">Fleet size</label>
        <input type="number" id="fleet_size" name="FleetSize" required />
        <div class="text-danger" id="fleetSizeError"></div>

        <label for="description">Description</label>
        <input type="text" id="description" name="Description" required />
        <div class="text-danger" id="descriptionError"></div>

        <button type="submit" class="block-button-style" id="submitButton">Submit</button>

        <div id="errorMessages" class="text-danger"></div>
    }
    <div class="loader-container">
        <div class="loader"></div>
    </div>
</div>

<div class="footer">
    <p>Rise Airlines 2024 ©</p>
</div>

<script src="~/js/showContent.js"></script>
<script src="~/js/airlineValidation.js"></script>
<script src="~/js/animation.js"></script>

Airlines.Web/Views/Airport/Index.cshtml
@model List<Airlines.Persistance.Models.Airport>
<partial name="_Notification" />

@{
    ViewData["Title"] = "Airports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-airlines">
    <div class="container-title">
        <a asp-controller="Home" asp-action="Index">
            <img src="~/Pictures/left sidebar.png" alt="bar" />
        </a>
        <h1>Airports</h1>
        <div></div>
    </div>

    <div class="container-head"></div>

    <div id="showSearchBar">
        <form action="@Url.Action("Search", "Airport")" method="get" class="search-form">
            <input type="text" name="searchTerm" placeholder="Search..." class="search-input" />
            <button type="submit" class="search-button">Search</button>
        </form>
    </div>

    <div class="table">
        <table>
            <thead>
                <tr>
                    <th class="table-header">Name</th>
                    <th class="table-header">Country</th>
                    <th class="table-header">City</th>
                    <th class="table-header">Code</th>
                    <th class="table-header">Runways</th>
                    <th class="table-header">Founded</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var airport in Model)
                {
                    <tr>
                        <td>@airport.Name</td>
                        <td>@airport.Country</td>
                        <td>@airport.City</td>
                        <td>@airport.Code</td>
                        <td>@airport.RunwaysCount</td>
                        <td>@airport.Founded</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <button id="showMore" class="block-button-airlines">Show More</button>
    <a href="#" id="toggleButton" class="block-button-airlines">Show Form</a>

    @using (Html.BeginForm("CreateNewAirport", "Airport", FormMethod.Post, new { @class = "form" }))
    {
        <legend>Add new Airport</legend>

        <label for="name">Name</label>
        <input type="text" id="name" name="Name" required />
        <div class="text-danger" id="nameError"></div>

        <label for="country">Country</label>
        <input type="text" id="country" name="Country" required />
        <div class="text-danger" id="countryError"></div>

        <label for="city">City</label>
        <input type="text" id="city" name="City" required />
        <div class="text-danger" id="cityError"></div>

        <label for="code">Code</label>
        <input type="text" id="code" name="Code" required />
        <div class="text-danger" id="codeError"></div>

        <label for="runways_count">Runways Count</label>
        <input type="number" id="runways_count" name="RunwaysCount" required />
        <div class="text-danger" id="runwaysError"></div>

        <label for="founded">Founded</label>
        <input type="date" id="founded" name="Founded" required />
        <div class="text-danger" id="foundedError"></div>

        <button type="submit" class="block-button-style" id="submitButton">Submit</button>

        <div id="errorMessages" class="text-danger"></div>
    }
    <div class="loader-container">
        <div class="loader"></div>
    </div>
</div>

<div class="footer">
    <p>Rise Airlines 2024 ©</p>
</div>

<script src="~/js/showContent.js"></script>
<script src="~/js/airportValidation.js"></script>
<script src="~/js/animation.js"></script>

Airlines.Web/Views/Flight/Index.cshtml
@model List<Airlines.Persistance.Models.Flight>
<partial name="_Notification" />

@{
    ViewData["Title"] = "Flights";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-airlines">
    <div class="container-title">
        <a asp-controller="Home" asp-action="Index">
            <img src="~/Pictures/left sidebar.png" alt="bar" />
        </a>
        <h1>Flights</h1>
        <div></div>
    </div>

    <div class="container-head"></div>

    <div id="showSearchBar">
        <form action="@Url.Action("Search", "Flight")" method="get" class="search-form">
            <input type="text" name="searchTerm" placeholder="Search..." class="search-input" />
            <button type="submit" class="search-button">Search</button>
        </form>
    </div>

    <div class="table">
        <table>
            <thead>
                <tr>
                    <th class="table-header">Flight number</th>
                    <th class="table-header">Departure Airport Id</th>
                    <th class="table-header">Arrival Airport Id</th>
                    <th class="table-header">Departure date & time</th>
                    <th class="table-header">Arrival date & time</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var flight in Model)
                {
                    <tr>
                        <td>@flight.FlightNumber</td>
                        <td>@flight.DepartureAirportId</td>
                        <td>@flight.ArrivalAirportId</td>
                        <td>@flight.DepartureDateTime</td>
                        <td>@flight.ArrivalDateTime</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <button id="showMore" class="block-button-airlines">Show More</button>
    <a href="#" id="toggleButton" class="block-button-airlines">Show Form</a>

    @using (Html.BeginForm("AddFlight", "Flight", FormMethod.Post, new { @class = "form" }))
    {
        <legend>Add new Flight</legend>

        <label for="FlightNumber">Flight Number</label>
        <input type="text" id="flightNumber" name="FlightNumber" required />
        <div class="text-danger" id="flightNumberError"></div>

        <label for="DepartureAirportId">Departure Airport Id</label>
        <input type="number" id="departureAirportId" name="DepartureAirportId" required />
        <div class="text-danger" id="departureAirportIdError"></div>

        <label for="ArrivalAirportId">Arrival Airport Id</label>
        <input type="number" id="arrivalAirportId" name="ArrivalAirportId" required />
        <div class="text-danger" id="arrivalAirportIdError"></div>

        <div class="columns-flight">
            <div class="columns-dep-arr">
                <label for="DepartureDateTime">Departure Date Time</label>
                <input type="datetime-local" id="departureDateTime" name="DepartureDateTime" required />
                <div class="text-danger" id="departureDateTimeError"></div>
            </div>

            <div class="columns-dep-arr">
                <label for="ArrivalDateTime">Arrival Date Time</label>
                <input type="datetime-local" id="arrivalDateTime" name="ArrivalDateTime" required />
                <div class="text-danger" id="arrivalDateTimeError"></div>
            </div>
        </div>

        <button type="submit" class="block-button-style" id="submitButton">Submit</button>

        <div id="errorMessages" class="text-danger"></div>
    }
    <div class="loader-container">
        <div class="loader"></div>
    </div>
</div>

<div class="footer">
    <p>Rise Airlines 2024 ©</p>
</div>

<script src="~/js/showContent.js"></script>
<script src="~/js/flightValidation.js"></script>
<script src="~/js/animation.js"></script>

Airlines.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "RISE-Airlines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="dashboard">
    <h2>Welcome To Dashboard</h2>
</div>

<div class="container">
    <div class="card-container">
        <div class="card">
            <div class="card-description">
                <p>Airports</p>
                <img class="image" src="~/Pictures/mdi_airport.png" alt="airport-image" />
                <p>@ViewBag.AirportCount</p>
            </div>
            <a asp-controller="Airport" asp-action="Index" class="block-button">Add New Airport</a>
        </div>

        <div class="card">
            <div class="card-description">
                <p>Airlines</p>
                <img class="image" src="~/Pictures/ri_plane-fill.png" alt="airline-image" />
                <p>@ViewBag.AirlineCount</p>
            </div>
            <a asp-controller="Airline" asp-action="Index" class="block-button">Add New Airline</a>
        </div>

        <div class="card">
            <div class="card-description">
                <p>Flights</p>
                <img class="image" src="~/Pictures/carbon_flight-schedule.png" alt="flight-image" />
                <p>@ViewBag.FlightCount</p>
            </div>
            <a asp-controller="Flight" asp-action="Index" class="block-button">Add New Flight</a>
        </div>
    </div>
</div>

Airlines.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/index.css">
    <link rel="stylesheet" href="~/css/style.css">
    <title>@ViewData["Title"]</title>
</head>
<body>
    <div class="nav-bar">
        <h4 class="nav-link-home">
            <a asp-controller="Home" asp-action="Index">Rise Airlines</a>
            <span><img src="~/Pictures/icon.png" class="nav-bar-icon"></span>
        </h4>
        <div class="nav-links">
            <a asp-controller="Airport" asp-action="Index">Airports</a>
            <a asp-controller="Airline" asp-action="Index">Airlines</a>
            <a asp-controller="Flight" asp-action="Index">Flights</a>
        </div>
    </div>

    <main class="content">
        @RenderBody()
    </main>

    <div class="footer">
        <p>Rise Airlines 2024 ©</p>
    </div>
</body>
</html>

Airlines.Web/Views/Shared/_Notification.cshtml
@if (TempData["SuccessMessage"] != null)
{
    <div class="success-message">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="error-message">
        @TempData["ErrorMessage"]
    </div>
}